<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\StockLocation;
use App\Models\StockMove;
use App\Models\User;
use Illuminate\Database\Seeder;

class OdooProductSeeder extends Seeder
{
    /**
     * Run the database seeds for Odoo Products (Benang Baju).
     */
    public function run(): void
    {
        $admin = User::first();
        $locMain = StockLocation::where('code', 'WH-MAIN')->first() 
            ?? StockLocation::firstOrCreate(['code' => 'WH-MAIN'], ['name' => 'Gudang Bahan Baku Utama', 'type' => 'internal']);
            
        $locSupplier = StockLocation::where('code', 'VENDOR-SUPP')->first() 
            ?? StockLocation::firstOrCreate(['code' => 'VENDOR-SUPP'], ['name' => 'Supplier Eksternal', 'type' => 'vendor']);

        $category = ProductCategory::where('name', 'Benang Baju')->first() 
            ?? ProductCategory::firstOrCreate(['name' => 'Benang Baju'], ['code' => 'CAT-BNG-BAJU']);

        $productsData = array (
  0 => 
  array (
    'row' => 3,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Black W 849_Fujitex',
    'brand' => '',
    'on_hand' => 5.39,
    'forecasted' => 5.39,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-BLAC-G100',
  ),
  1 => 
  array (
    'row' => 4,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Blue W 864_Fujitex',
    'brand' => '',
    'on_hand' => 10.2,
    'forecasted' => 10.2,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-BLUE-G100',
  ),
  2 => 
  array (
    'row' => 5,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Cream W 900_Fujitex',
    'brand' => '',
    'on_hand' => 10.81,
    'forecasted' => 10.81,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-CREA-G100',
  ),
  3 => 
  array (
    'row' => 6,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Grey W 825_Fujitex',
    'brand' => '',
    'on_hand' => 12.09,
    'forecasted' => 12.09,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-GREY-G100',
  ),
  4 => 
  array (
    'row' => 7,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_LT Blue W 909_Fujitex',
    'brand' => '',
    'on_hand' => 10.98,
    'forecasted' => 10.98,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-LT-G100',
  ),
  5 => 
  array (
    'row' => 8,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Maroon W 805_Fujitex',
    'brand' => '',
    'on_hand' => 12.48,
    'forecasted' => 12.48,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-MARO-G100',
  ),
  6 => 
  array (
    'row' => 9,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Mocca W 872_Fujitex',
    'brand' => '',
    'on_hand' => 11.96,
    'forecasted' => 11.96,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-MOCC-G100',
  ),
  7 => 
  array (
    'row' => 10,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_Peach W 925_Fujitex',
    'brand' => '',
    'on_hand' => 6.71,
    'forecasted' => 10,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-PEAC-G100',
  ),
  8 => 
  array (
    'row' => 11,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 100 % Polyester_White W 821_Fujitex',
    'brand' => '',
    'on_hand' => 12.18,
    'forecasted' => 12.18,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-PLY-WHIT-G100',
  ),
  9 => 
  array (
    'row' => 12,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscoce_Salem 1859_Toko Aneka',
    'brand' => '',
    'on_hand' => 11.16,
    'forecasted' => 11.16,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-SALE-28',
  ),
  10 => 
  array (
    'row' => 13,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose Denim Tua 1835T_Toko Aneka',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 0,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-TOKO-28',
  ),
  11 => 
  array (
    'row' => 14,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Biru Baby 1819_Toko Aneka',
    'brand' => '',
    'on_hand' => 10.09,
    'forecasted' => 10.09,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-BIRU-28',
  ),
  12 => 
  array (
    'row' => 15,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Biru Sedang 5238 (D538)_Toko Aneka',
    'brand' => '',
    'on_hand' => 109.79,
    'forecasted' => 29.13921,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-BIRU-28-2',
  ),
  13 => 
  array (
    'row' => 16,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Broken White/Off White 6002 (D037)_Toko Aneka',
    'brand' => '',
    'on_hand' => 565.36,
    'forecasted' => -265.07439,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-BROK-28',
  ),
  14 => 
  array (
    'row' => 17,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Burgundy/Maroon1919(D077)_Toko Aneka',
    'brand' => '',
    'on_hand' => 198.55,
    'forecasted' => -141.38184,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-BURG-28',
  ),
  15 => 
  array (
    'row' => 18,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Coklat 1809(D400)_Toko Aneka',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => -1.5192,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-COKL-28',
  ),
  16 => 
  array (
    'row' => 19,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Coklat Milo/Cream Sedang 1808(D060)_Toko Aneka',
    'brand' => '',
    'on_hand' => 57.96,
    'forecasted' => 2.69358,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-COKL-28-2',
  ),
  17 => 
  array (
    'row' => 20,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Coklat Muda 4268_Toko Aneka (persamaan B101 Fujitex)',
    'brand' => '',
    'on_hand' => 189.12,
    'forecasted' => 143.3248,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-COKL-28-3',
  ),
  18 => 
  array (
    'row' => 21,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Cream 1807(D282)_Toko Aneka',
    'brand' => '',
    'on_hand' => 30.49,
    'forecasted' => 18.1384,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-CREA-28',
  ),
  19 => 
  array (
    'row' => 22,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Hijau Army/Army Green 1897(D122)_Toko Aneka',
    'brand' => '',
    'on_hand' => 21.1,
    'forecasted' => -97.34775,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-HIJA-28',
  ),
  20 => 
  array (
    'row' => 23,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Hijau/Alpukat Muda 083_Toko Aneka',
    'brand' => '',
    'on_hand' => 11.11,
    'forecasted' => 11.11,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-HIJA-28-2',
  ),
  21 => 
  array (
    'row' => 24,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Hitam 1920_Toko Aneka',
    'brand' => '',
    'on_hand' => 520.01,
    'forecasted' => 532.81,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-HITA-28',
  ),
  22 => 
  array (
    'row' => 25,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Misty Muda M71(D056)_Toko Aneka',
    'brand' => '',
    'on_hand' => 103.06,
    'forecasted' => 23.49355,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-MIST-28',
  ),
  23 => 
  array (
    'row' => 26,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Misty Tua M81(D239)_Toko Aneka',
    'brand' => '',
    'on_hand' => 32.09,
    'forecasted' => 17.6968,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-MIST-28-2',
  ),
  24 => 
  array (
    'row' => 27,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Mocca 5331(D042)_Toko Aneka',
    'brand' => '',
    'on_hand' => 19.93,
    'forecasted' => 19.93,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-MOCC-28',
  ),
  25 => 
  array (
    'row' => 28,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Navy Muda 1839M(D038)_Toko Aneka',
    'brand' => '',
    'on_hand' => 61.28,
    'forecasted' => -25.38874,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-NAVY-28',
  ),
  26 => 
  array (
    'row' => 29,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Olive Green/Alpukat Tua1895(D131)_Toko Aneka',
    'brand' => '',
    'on_hand' => 47.38,
    'forecasted' => -3.53644,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-OLIV-28',
  ),
  27 => 
  array (
    'row' => 30,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Orange/Brick Red 1933_Toko Aneka',
    'brand' => '',
    'on_hand' => 11.19,
    'forecasted' => 11.19,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-ORAN-28',
  ),
  28 => 
  array (
    'row' => 31,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Pink 1871(D289)_Toko Aneka',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 0,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-PINK-28',
  ),
  29 => 
  array (
    'row' => 32,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Pink Tua 1876_Toko Aneka',
    'brand' => '',
    'on_hand' => 11.06,
    'forecasted' => 11.06,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-PINK-28-2',
  ),
  30 => 
  array (
    'row' => 33,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Putih 1801 (B 013)_Toko Aneka',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 0,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-PUTI-28',
  ),
  31 => 
  array (
    'row' => 34,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Red/Burgundy 1904_Toko Aneka',
    'brand' => '',
    'on_hand' => 10.66,
    'forecasted' => 10.66,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-RED/-28',
  ),
  32 => 
  array (
    'row' => 35,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Steel Blue 5238T_Toko Aneka',
    'brand' => '',
    'on_hand' => 94.91,
    'forecasted' => 70.3866,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-STEE-28',
  ),
  33 => 
  array (
    'row' => 36,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang 2/28 Rayon Viscose_Ungu/Light Purple 1911_Toko Aneka',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 10,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-RAY-UNGU-28',
  ),
  34 => 
  array (
    'row' => 37,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Apricot 267_Fujitex',
    'brand' => '',
    'on_hand' => 30.27,
    'forecasted' => 30.27,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-APRI-T267',
  ),
  35 => 
  array (
    'row' => 38,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Army B 122_Fujitex',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 0,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-ARMY-B122',
  ),
  36 => 
  array (
    'row' => 39,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Black B 006_Fujitex',
    'brand' => '',
    'on_hand' => 466.71,
    'forecasted' => -352.90431,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-BLAC-B006',
  ),
  37 => 
  array (
    'row' => 40,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Browen B 101_Fujitex',
    'brand' => '',
    'on_hand' => 101.25,
    'forecasted' => -468.23199,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-BROW-B101',
  ),
  38 => 
  array (
    'row' => 41,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Browen B 147_Fujitex',
    'brand' => '',
    'on_hand' => 6.1,
    'forecasted' => 6.1,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-BROW-B147',
  ),
  39 => 
  array (
    'row' => 42,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Camel B 049_Fujitex',
    'brand' => '',
    'on_hand' => 21.56,
    'forecasted' => -22953.01898,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-CAME-B049',
  ),
  40 => 
  array (
    'row' => 43,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Cream 21-0608_Fujitex',
    'brand' => '',
    'on_hand' => 21.45,
    'forecasted' => 0.13429,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-CREA-M21',
  ),
  41 => 
  array (
    'row' => 44,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_DK Green B 022_Fujitex',
    'brand' => '',
    'on_hand' => 10.73,
    'forecasted' => 10.73,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-DK-B022',
  ),
  42 => 
  array (
    'row' => 45,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Dark Green Chartreuse B 315_Fujitex',
    'brand' => '',
    'on_hand' => 18.39,
    'forecasted' => 30.9,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-DARK-B315',
  ),
  43 => 
  array (
    'row' => 46,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Dusty Pink B 181_Fujitex',
    'brand' => '',
    'on_hand' => 16.77,
    'forecasted' => 16.77,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-DUST-B181',
  ),
  44 => 
  array (
    'row' => 47,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Green  B 110_Fujitex',
    'brand' => '',
    'on_hand' => 5.91,
    'forecasted' => 5.91,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-GREE-B110',
  ),
  45 => 
  array (
    'row' => 48,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Green B 241_Fujitex',
    'brand' => '',
    'on_hand' => 66.66,
    'forecasted' => 30.03458,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-GREE-B241',
  ),
  46 => 
  array (
    'row' => 49,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Green Chatreuse B 268_Fujitex',
    'brand' => '',
    'on_hand' => 10.74,
    'forecasted' => 10.74,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-GREE-B268',
  ),
  47 => 
  array (
    'row' => 50,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Green Olive B 242_Fujitex',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 3.89,
    'sales_price' => 1,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-GREE-B242',
  ),
  48 => 
  array (
    'row' => 51,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Grey B 056_Fujitex',
    'brand' => '',
    'on_hand' => 30.13,
    'forecasted' => 30.13,
    'sales_price' => 0,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-GREY-B056',
  ),
  49 => 
  array (
    'row' => 52,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Khaki Melange 060_Fujitex',
    'brand' => '',
    'on_hand' => 42.08,
    'forecasted' => 42.08,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-KHAK-E060',
  ),
  50 => 
  array (
    'row' => 53,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_LT Blue B 256_Fujitex',
    'brand' => '',
    'on_hand' => 10.82,
    'forecasted' => 8.599,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LT-B256',
  ),
  51 => 
  array (
    'row' => 54,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_LT Sky Blue B202_Fujitex',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 30,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LT-B202',
  ),
  52 => 
  array (
    'row' => 55,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Lavender B 144_Fujitex',
    'brand' => '',
    'on_hand' => 10.48,
    'forecasted' => 10.48,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LAVE-B144',
  ),
  53 => 
  array (
    'row' => 56,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Light Cream B 313_Fujitex',
    'brand' => '',
    'on_hand' => 32.16,
    'forecasted' => 32.16,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LIGH-B313',
  ),
  54 => 
  array (
    'row' => 57,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Light Green B 214/297_Fujitex',
    'brand' => '',
    'on_hand' => 6.09,
    'forecasted' => 16.09,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LIGH-B214',
  ),
  55 => 
  array (
    'row' => 58,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Light Sky Blue B 180_Fujitex',
    'brand' => '',
    'on_hand' => 31.56,
    'forecasted' => 13.3808,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-LIGH-B180',
  ),
  56 => 
  array (
    'row' => 59,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Maroon B 077_Fujitex',
    'brand' => '',
    'on_hand' => 230.37,
    'forecasted' => 81.72392,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-MARO-B077',
  ),
  57 => 
  array (
    'row' => 60,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Mocca B 042_Fujitex',
    'brand' => '',
    'on_hand' => 32.89,
    'forecasted' => -4.49041,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-MOCC-B042',
  ),
  58 => 
  array (
    'row' => 61,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Navy B 038_Fujitex',
    'brand' => '',
    'on_hand' => 30.77,
    'forecasted' => 30.77,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-NAVY-B038',
  ),
  59 => 
  array (
    'row' => 62,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Oatmeal/Cream B 059_Fujitex',
    'brand' => '',
    'on_hand' => 119.31,
    'forecasted' => 42.38588,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-OATM-B059',
  ),
  60 => 
  array (
    'row' => 63,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Peach B 162_Fujitex',
    'brand' => '',
    'on_hand' => 10.7,
    'forecasted' => 10.7,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-PEAC-B162',
  ),
  61 => 
  array (
    'row' => 64,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Pink B 107_Fujitex',
    'brand' => '',
    'on_hand' => 0,
    'forecasted' => 10,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-PINK-B107',
  ),
  62 => 
  array (
    'row' => 65,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Soft Pink B 212_Fujitex',
    'brand' => '',
    'on_hand' => 314.72,
    'forecasted' => 18.55995,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-SOFT-B212',
  ),
  63 => 
  array (
    'row' => 66,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_White B 037_Fujitex',
    'brand' => '',
    'on_hand' => 277.83,
    'forecasted' => 183.20122,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-WHIT-B037',
  ),
  64 => 
  array (
    'row' => 67,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Yellow B 125_Fujitex',
    'brand' => '',
    'on_hand' => 10.4,
    'forecasted' => 10.4,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-YELL-B125',
  ),
  65 => 
  array (
    'row' => 68,
    'category' => 'Benang Baju',
    'internal_reference' => '',
    'name' => 'Benang DTY_Yellow Crayola B 065_Fujitex',
    'brand' => '',
    'on_hand' => 106.23,
    'forecasted' => 46.8974,
    'sales_price' => 2,
    'cost' => 0,
    'uom' => 'kg',
    'tags' => '',
    'code' => 'BNG-DTY-YELL-B065',
  ),
);

        foreach ($productsData as $index => $item) {
            $vendor = null;
            if (stripos($item['name'], 'Fujitex') !== false) {
                $vendor = 'Fujitex';
            } elseif (stripos($item['name'], 'Toko Aneka') !== false) {
                $vendor = 'Toko Aneka';
            }

            // Standard estimate cost if 0
            $costPrice = $item['cost'] > 0 ? $item['cost'] : 65000;
            $salePrice = $item['sales_price'] > 0 ? $item['sales_price'] : 0;

            $product = Product::updateOrCreate(
                ['code' => $item['code']],
                [
                    'name' => $item['name'],
                    'type' => 'raw_material',
                    'category_id' => $category->id,
                    'category' => $category->name,
                    'uom' => $item['uom'] ?: 'kg',
                    'uom_po' => $item['uom'] ?: 'kg',
                    'tracking' => 'lot',
                    'route_buy' => true,
                    'route_manufacture' => false,
                    'can_be_sold' => true,
                    'can_be_purchased' => true,
                    'min_stock' => 50,
                    'max_stock' => 1000,
                    'reorder_qty' => 100,
                    'cost_price' => $costPrice,
                    'sale_price' => $salePrice,
                    'preferred_vendor' => $vendor,
                    'costing_method' => 'average',
                    'valuation_method' => 'automated',
                    'is_active' => true,
                    'description' => 'Odoo Product: ' . $item['name'],
                ]
            );

            // Record Initial Physical Stock if On Hand > 0
            $onHand = (float) $item['on_hand'];
            if ($onHand > 0) {
                $moveNum = 'SM-ODOO-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);
                StockMove::firstOrCreate(
                    ['move_number' => $moveNum],
                    [
                        'product_id' => $product->id,
                        'from_location_id' => $locSupplier->id,
                        'to_location_id' => $locMain->id,
                        'qty' => $onHand,
                        'uom' => $product->uom,
                        'category' => StockMove::CAT_PO_RECEIPT,
                        'reference_type' => 'InitialStock',
                        'reference_number' => 'ODOO-INIT-' . $product->code,
                        'batch_lot_number' => 'LOT-' . substr($product->code, -8),
                        'notes' => 'Initial On Hand Stock from Odoo Import',
                        'created_by' => $admin?->id,
                    ]
                );
            }
        }
    }
}
