<livewire:chatter-panel
    :record="$record"
    :resource-class="$resourceClass"
    :message-mail-view-path="$messageMailViewPath"
    :follower-mail-view-path="$followerMailViewPath"
    :is-message-action-visible="$isMessageActionVisible"
    :is-log-action-visible="$isLogActionVisible"
    :is-activity-action-visible="$isActivityActionVisible"
    :is-follower-action-visible="$isFollowerActionVisible"
    :is-file-action-visible="$isFileActionVisible"
    :activity-plans="$activityPlans"
    lazy
/>